---
- name: Reload Kea configuration
  ansible.builtin.command: /usr/local/bin/keactrl reload
  register: kea_reload_result
  changed_when:
    - '"INFO/keactrl: Reloading kea-dhcp4..." in kea_reload_result.stdout'
