---
- name: Apply role to hosts
  hosts: all
  become: true
  vars:
    monitoring_system: true
    generate_systemd: true
    pcp_clients:
      - 192.168.122.2
      - 192.168.122.63
  roles:
    - role: setup_pcp
