---

- name: Setup and install packages
  hosts: alphost
  vars:
    package_installer_role_switches:
      alp_workload_ansible: true
      alp_workload_cockpit-ws: false
      alp_workload_neuvector: false
      alp_docker: false
      system_role_ssh: false
      system_role_selinux: false
      system_role_network: false
      system_role_timesync: false
      system_role_systemd: false
      system_role_cockpit_minimal: false
      system_role_cockpit_default: false
      system_role_cockpit_full: false
      system_role_journald: false
      system_role_kernal_settings: false
  roles:
    - package_installer
