---
- name: Setup ALP workloads
  hosts: alptestvm
  become: true
  roles:
    - role: setup_alp_workloads
      vars:
        setup_cockpit: false
        setup_firewalld: false
        setup_grafana: false
        setup_keylime: false
        setup_kea_dhcpv6_server: false
        setup_kea_dhcpv4_server: false
        setup_neuvector: false
        setup_ansible: true
