---

- name: Gather packages for enabled roles
  ansible.builtin.set_fact:
    package_installer_packages_to_install: "{{ package_installer_packages_to_install | default([]) + [item.1] }}"
  loop: "{{ package_installer_role_packages | dict2items | subelements('value') }}"
  when: package_installer_role_switches[item.0.key]

- name: Display packages to be installed
  ansible.builtin.debug:
    msg: "Packages to be installed: {{ package_installer_packages_to_install | unique | sort }}"

- name: Prompt for installation confirmation
  ansible.builtin.pause:
    prompt: "Do you want to proceed with installing the above packages on all hosts? (yes/no)"
  register: user_input

- name: Include task install_packages
  ansible.builtin.include_tasks: install_packages
  when: user_input.user_input | lower == 'yes'
