---
package_installer_role_packages:
  alp_workload_ansible:
    - kernel-default
    - "-kernel-default-base"
    - python3-libvirt-python
    - python3-lxml
    - python3-rpm
  alp_workload_cockpit-ws:
    - cockpit-bridge
    - cockpit-tukit
    - "-cockpit-ws"
  alp_workload_neuvector:
    - python3-selinux
  alp_docker:
    - docker
  system_role_ssh:
    - openssh
    - openssh-clients
  system_role_selinux:
    - python3-selinux
    - python3-policycoreutils
  system_role_network:
    - NetworkManager
    - wpa_supplicant
    - openssl
    - ethtool
  system_role_timesync:
    - chrony
  system_role_systemd:
    - systemd
  system_role_cockpit_minimal:
    - cockpit-system
    - cockpit-ws #Do not install if using containerised cockpit
  system_role_cockpit_default:
    - cockpit-bridge
    - cockpit-networkmanager
    - cockpit-selinux
    - cockpit-storaged
  system_role_cockpit_full:
    - cockpit-bridge
    - cockpit-machines
    - cockpit-networkmanager
    - cockpit-podman
    - cockpit-selinux
    - cockpit-storaged
    - cockpit-tukit
  system_role_journald:
    - systemd
  system_role_kernal_settings:
    - tuned
    - python-configobj
