---
- name: Deploy the container(s)
  containers.podman.podman_container:
    name: "{{ item.name }}"
    command: "{{ item.command | default(omit) }}"
    detach: "{{ item.detach | default('yes') }}"
    env: "{{ item.env | default(omit) }}"
    image: "{{ item.image | default(omit) }}"
    labels: "{{ item.labels | default(omit) }}"
    network: "{{ item.networks | default(omit) }}"
    publish: "{{ item.published_ports | default(omit) }}"
    restart_policy: "{{ item.restart_policy | default(omit) }}"
    state: "{{ item.state | default('started') }}"
    volume: "{{ item.volumes | default(omit) }}"
    cap_add: "{{ item.capabilities | default(omit) }}"
    cap_drop: "{{ item.cap_drop | default(omit) }}"
    cpu_shares: "{{ item.cpu_shares | default(omit) }}"
    cpus: "{{ item.cpus | default(omit) }}"
    dns: "{{ item.dns_servers | default(omit) }}"
    healthcheck:
    healthcheck_interval: "{{ item.healthcheck_interval | default(omit) }}"
    healthcheck_timeout: "{{ item.healthcheck_timeout | default('30s') }}"
    healthcheck_start_period: "{{ item.healthcheck_start_period | default('0s') }}"
    healthcheck_retries: "{{ item.healthcheck_retries | default(3) }}"
    hostname: "{{ item.hostname | default(omit) }}"
    init: "{{ item.init | default('no') }}"
    memory: "{{ item.memory | default('0') }}"
    pod: "{{ item.pod | default(omit) }}"
    privileged: "{{ item.privileged | default('no') }}"
    read_only: "{{ item.read_only | default('no') }}"
    rm: "{{ item.auto_remove | default('no') }}"
    security_opt: "{{ item.security_opt | default(omit) }}"
    sysctl: "{{ item.sysctl | default(omit) }}"
    tmpfs: "{{ item.tmpfs | default(omit) }}"
    shm_size: "{{ item.shm_size | default(omit) }}"
    cpu_quota: "{{ item.cpu_quota | default(omit) }}"
    cpu_period: "{{ item.cpu_period | default(omit) }}"
    cpuset_cpus: "{{ item.cpuset_cpus | default(omit) }}"
    cpuset_mems: "{{ item.cpuset_mems | default(omit) }}"
    network_aliases: "{{ item.network_aliases | default(omit) }}"
  loop: "{{ podman_containers }}"
  when: podman_containers is defined
# to-do add more parameters
