---
- name: Setup the network
  containers.podman.podman_network:
    name: "{{ item.name }}"
    debug: "{{ item.debug | default(false) }}"
    disable_dns: "{{ item.disable_dns | default(false) }}"
    driver: "{{ item.driver | default('bridge') }}"
    executable: "{{ item.executable | default('podman') }}"
    gateway: "{{ item.gateway | default(omit) }}"
    internal: "{{ item.internal | default(false) }}"
    ip_range: "{{ item.ip_range | default(omit) }}"
    ipv6: "{{ item.ipv6 | default(false) }}"
    macvlan: "{{ item.macvlan | default(omit) }}"
    opt: "{{ item.opt | default(omit) }}"
    metric: "{{ item.metric | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    mtu: "{{ item.mtu | default(omit) }}"
    parent: "{{ item.parent | default(omit) }}"
    vlan: "{{ item.vlan | default(omit) }}"
    recreate: "{{ item.recreate | default(false) }}"
    state: "{{ item.state | default('present') }}"
    subnet: "{{ item.subnet | default(omit) }}"
  loop: "{{ podman_networks }}"
  when: podman_networks is defined
