---
- name: Reboot system
  ansible.builtin.reboot:
    msg: "Rebooting to apply changes switching to NetworkManager"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 60
    test_command: whoami
