---
- name: Install required packages, if any, for workload cockpit
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  notify: Reboot
  loop:
    - cockpit-bridge
    - cockpit-tukit
    - "-cockpit-ws"

- name: Reboot right now if necessary
  ansible.builtin.meta: flush_handlers

- name: Retrieve image for workload cockpit
  containers.podman.podman_image:
    name: "{{ cockpit_image }}"
    state: present

- name: Install Cockpit Web server container
  containers.podman.podman_runlabel:
    image: "{{ cockpit_image }}"
    label: INSTALL

- name: Ensure service can be started for workload cockpit
  ansible.builtin.systemd_service:
    name: "cockpit.service"
    state: "started"
    enabled: true

- name: Inform user to access the Cockpit Web user interface
  ansible.builtin.debug:
    msg: >-
      Cockpit Web UI is running on https://{{ ansible_default_ipv4.address }}:9090
      Please accept the warning about the self-signed SSL certificate to access it.
