---
- name: Start and enable Grafana using systemd
  ansible.builtin.service:
    name: grafana
    state: started
    enabled: true

- name: Display Grafana access information
  ansible.builtin.debug:
    msg:
      - "Please open the Grafana UI at http://{{ ansible_default_ipv4.address }}:3000."
      - "Log in to Grafana. The default user name and password are both set to 'admin'. After logging in, enter a new password."
      - "Follow the on-screen prompts to complete the configuration."
