---
- name: Install required packages, if any, for workload ansible
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  notify: Reboot
  loop:
    - kernel-default
    - "-kernel-default-base"
    - python3-libvirt-python
    - python3-lxml
    - python3-rpm

- name: Reboot right now if necessary
  ansible.builtin.meta: flush_handlers

- name: Retrieve image for workload ansible
  containers.podman.podman_image:
    name: "{{ ansible_image }}"
    state: present

- name: Install ansible container
  containers.podman.podman_runlabel:
    image: "{{ ansible_image }}"
    label: INSTALL

- name: Ping localhost to check Ansible
  ansible.builtin.ping:
  register: ping_result

- name: Display success message if ping succeeds
  ansible.builtin.debug:
    msg: "Ansible is installed and working correctly. Ping result: {{ ping_result.ping }}"
  when: ping_result is defined and ping_result.ping == "pong"
