---
- name: Ensure polkit daemon is restarted (if necessary)
  ansible.builtin.service:
    name: polkit
    state: restarted
  when:
    - "'etc/polkit-1/actions/org.fedoraproject.FirewallD1.policy' in workload_runlabel_install.stdout"

- name: Start and enable firewalld using systemd
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Display completion message
  ansible.builtin.debug:
    msg: >-
      "Firewalld workload setup complete."
      "Use the /usr/local/bin/firewall-cmd wrapper to manage the firewalld instance."
