---
- name: Retrieve images for Keylime
  containers.podman.podman_image:
    name: "{{ keylime_image }}"
    state: present

- name: Start the Keylime container and related services
  containers.podman.podman_runlabel:
    image: "{{ keylime_image }}"
    label: INSTALL

- name: Display completion message
  ansible.builtin.debug:
    msg: >-
      "Keylime setup and tenant CLI execution completed successfully."
