---
- name: Ensure service can be started for workload {{ workload.name }}
  ansible.builtin.systemd_service:
    name: "cockpit.service"
    state: "started"
    enabled: true

- name: Inform user to access the Cockpit Web user interface
  ansible.builtin.debug:
    msg: >-
      Cockpit Web UI is running on https://{{ ansible_default_ipv4.address }}:9090
      Please accept the warning about the self-signed SSL certificate to access it.
