---
- name: Pull the Kea DHCP server container image
  containers.podman.podman_image:
    name: "{{ kea_image }}"
    state: present

- name: Install all required parts of the Kea workload
  containers.podman.podman_runlabel:
    image: "{{ kea_image }}"
    label: INSTALL

- name: Add firewall exception rule for DHCP
  ansible.posix.firewalld:
    service: dhcpv6
    permanent: true
    state: enabled
    immediate: true

- name: Configure Kea DHCPv6 using template
  ansible.builtin.template:
    src: "kea-dhcp6.conf.j2"
    dest: "/etc/kea/kea-dhcp6.conf"
    mode: "0644"
  notify: Reload Kea configuration

- name: Start Kea DHCPv6 server using systemd
  ansible.builtin.systemd:
    name: kea-dhcp6.service
    state: started
    enabled: true
