---
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: "rpm"

- name: Fail if firewalld is installed locally
  ansible.builtin.fail:
    msg: "Firewalld is installed locally. Please remove it before installing this container."
  when: "'firewalld' in ansible_facts.packages"

- name: Retrieve image for workload
  containers.podman.podman_image:
    name: "{{ firewalld_image }}"
    state: present

- name: Initialize the environment
  containers.podman.podman_runlabel:
    image: "{{ firewalld_image }}"
    label: INSTALL
  register: workload_runlabel_install

- name: Ensure polkit daemon is restarted (if necessary)
  ansible.builtin.service:
    name: polkit
    state: restarted
  when:
    - workload_runlabel_install is changed

- name: Start and enable firewalld using systemd
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Display completion message
  ansible.builtin.debug:
    msg: >-
      "Firewalld workload setup complete."
      "Use the /usr/local/bin/firewall-cmd wrapper to manage the firewalld instance."
