---
- name: Create directory for each client to store recorded logs
  ansible.builtin.file:
    path: "{{ pcp_archives_dir }}/{{ client }}"
    state: directory
    mode: "644"
  when: pcp_container_state | default('started') != 'absent'

- name: Create pmlogger configuration file for each client
  ansible.builtin.template:
    src: "control.CLIENT.j2"
    dest: "{{ pcp_archives_dir }}/{{ client }}/control.{{ client }}"
    mode: "644"
  when: pcp_container_state | default('started') != 'absent'

- name: Retrieve image for PCP
  containers.podman.podman_image:
    name: "{{ pcp_image }}"
    state: present

- name: Create a pod for pcp containers
  containers.podman.podman_pod:
    name: "{{ pcp_container_name }}"
    state: "{{ pcp_container_state | default('created') }}"
  run_once: true

- name: Run PCP container with custom configurations
  containers.podman.podman_container:
    name: "{{ pcp_container_name }}-{{ client }}"
    image: "{{ pcp_image }}"
    systemd: always
    privileged: true
    env:
      PCP_SERVICES: pmlogger
    volumes:
      - "{{ pcp_archives_dir }}:/var/log/pcp/pmlogger:z"
      - "{{ pcp_archives_dir }}/{{ client }}/control.{{ client }}:/etc/pcp/pmlogger/control.d/local:z"
    state: "{{ pcp_container_state | default('created') }}"
    restart_policy: always
    pod: "{{ pcp_container_name }}"
  register: create_container
